### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by hafizbistar** [esnme/ultramysql#32]
LINK : error LNK2001: unresolved external symbol PyInit_umysql build\temp.win32-3.3\Release./python\umysql.lib : fatal error LNK1120: 1 unresolved externals
error: command '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe"' failed with exit status 1120

I am running Windows 7 x64
I have Visual Studio 9, 10, 11 (2008, 2010, 2012)
I am running under Python 3.3 environment.
MySQL connector for C/C++/Python are installed.

I had minor hiccups along the way, but this one, i really have no idea how to solve. have always been a problem for me to solve 'link' issue when compiling C/C++

**Comment by jskorpan** [comment]
Looks like you are compiling for Python 3.3

AFAIK umysql isn’t compatible with Python 3.3

//JT

**Comment by hafizbistar** [comment]
Yes, i am very new to python didn't realized that sooner. but it would surely help if there is a note saying it only support python 2.x

I am currently, trying to get it to work on python 3.3
i manage to compile it, but the tests.py crash during executions 
:|
